pipeline {
    agent any

    stages {
        stage('without docker') {
            steps {
                sh ''' 
                    echo "Without Docker"
                    ls -la
                    touch container-no.txt
                    ls -la

                '''
            }
        }

        stage('with docker') {
            agent{
                docker {
                    image 'node:18-alpine'
                }
            }
            steps {
                sh ''' 
                    echo "With Docker"
                    npm -version
                    ls -la
                    touch container-yes.txt
                    ls -la
                '''
            }
        }

    }
}
